### ISSUE TITLE
Improvements on COV

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/rubix-os#83]
Let's say for example, we need to record temperature and it is recorded at `24 °C` where the threshold is `2` but the temperature increases in our system by just `1` at a time and reaches `50 °C`, it doesn't record such value any value than that first `24 °C`

We need to compare with previously recorded cov `present_value` instead of the current `present_value`. That means we can have a field like `present_value_cov` to store that value, and we can compare it with it.

_Originally posted by @RaiBnod in https://github.com/NubeIO/rubix-os/pull/82#pullrequestreview-1503183155_

**Comment by CanuckMarc** [comment]
@enjuthulung  I had a look at your PR because I thought it was for something else, see my comment (https://github.com/NubeIO/rubix-os/pull/89#discussion_r1247218963).  But also consider my thoughts on the issue below.

I think there might be 2 concepts that are being confused here.  

1. **Present Value COV** - This concept would be to limit the number of DB updates that are done due to small changes in the point value.  Having a `PresentValueCOVThreshold` would mean that if the point changed by less than that threshold, the PRESENT VALUE wouldn't change (and therefore no DB update).  We haven't implemented this concept in FF or RubixOS, it was implemented on the old `point-server`.  We should definitely consider adding this feature sometime.

2. **History Value COV** - This concept is similar but has to do with storing new HISTORY values, not with PresentValue updates.  This is the one we are trying to implement here!  The only comparison that needs to be made is between the last stored HISTORY value, and the updated PresentValue.  

I suggest removing the `PresentValueCOV` property on `Point` (https://github.com/NubeIO/nubeio-rubix-lib-models-go/pull/76).  Instead add a property called `LastHistoryValue`, this stores the value of the last stored history.  Then the only comparison that needs to be made is whether the absolute difference between `PresentValue` and the `LastHistoryValue` is greater or equal to the `HistoryCOVThreshold`.
